Repository NatanimA/Javascript-capstone-project, pull requests merged in 2022-10, with the labels that each got.

#22 Project wireframes
  dist/index.bundle.js
  dist/index.html
  package-lock.json
  package.json
  src/assets/century-logo.png
  src/index.html
  src/js/index.js
  src/style.css
  webpack.config.js
Labels: documentation, enhancement

#24 Comments feature
  dist/index.bundle.js
  dist/index.html
  package-lock.json
  package.json
  src/assets/century-logo.png
  src/index.html
  src/js/index.js
  src/js/modules/apiUtility.js
  src/js/modules/comment.js
  src/js/modules/display.js
  src/style.css
  webpack.config.js
Labels: bug, enhancement

#25 Likes feature
  dist/index.bundle.js
  dist/index.html
  src/index.html
  src/js/index.js
  src/js/modules/comment.js
  src/js/modules/display.js
  src/js/modules/likes.js
  src/style.css
Labels: documentation, enhancement

#26 Bugs fix
  dist/index.bundle.js
  dist/index.html
  src/assets/century-logo.png
  src/index.html
  src/js/index.js
  src/js/modules/display.js
  src/js/modules/likes.js
  src/style.css
Labels: bug
